[package]
name = "monorepo-deps"
version = "0.1.0"
authors = ["Elie Genard <elie@lepermislibre.fr>"]
edition = "2018"

[dependencies]
serde = "^1.0.0"
serde_derive = "^1.0.0"
serde_json = "^1.0.0"
clap = "^2.32.0"
petgraph = "0.4.13"